### ISSUE TITLE
not compatible with ruby 1.8.7

### ISSUE THREAD

**Issue by fraenki** [chrekh/puppet-hosts#2]
Well, some of us still have to manage RHEL 6.x hosts (and it is still supported by RedHat). Unfortunately, it runs ruby 1.8.7 and thus is not compatible with the _puppet-hosts_ module:

```
Error: Could not retrieve local facts: undefined method `ip_address_list' for Socket:Class
Error: Failed to apply catalog: Could not retrieve local facts: undefined method `ip_address_list' for Socket:Class
```

The `list_addrs.rb` script utilizes the `ip_address_list` function, which is [not available on ruby 1.8.7](http://apidock.com/ruby/v1_8_7_330/Socket). A different approach is [demonstrated here](https://github.com/puppetlabs/facter/blob/2.x/lib/facter/interfaces.rb).

Would you consider to change the script accordingly?

**Comment by chrekh** [comment]
Asolutely.

But I don't quite understand.  I don't seem to have 'facter/util/ip'
or 'facter/util/macaddress' on my system. Do I need to install some
lib or something to get those?

**Comment by fraenki** [comment]
@chrekh Thanks for considering this change. These facter modules were already available [in facter 1.6.x](https://github.com/puppetlabs/facter/tree/1.6.x/lib/facter/util), so I guess they should be available everywhere.
On Debian you'll find them under `/usr/lib/ruby/vendor_ruby/facter/util` and on RedHat they're installed under `/usr/share/ruby/vendor_ruby/facter/util`. HTH

**Comment by chrekh** [comment]
One possible way to do this could be to require 'facter/util/ip' if
ip_address_list is not available

I don't have access to any host with facter 1.6 (or ruby 1.8) so I
can't test this.

I have prepared a patch that does this, and since it still uses
ip_address_list if available it shouldn't break on any host it's
workin on now at least.

Could you try c2e9b1e ? and if it needs tuning, just create a alternate
patch and let me try that

**Comment by fraenki** [comment]
Just tested your fix, but got some undefined variables:

```
Error: Could not retrieve local facts: undefined local variable or method `ipaddress' for main:Object
Error: Failed to apply catalog: Could not retrieve local facts: undefined local variable or method `ipaddress' for main:Object
```

```
Error: Could not retrieve local facts: undefined method `ipv4_loopback?' for "a.b.c.d":String
Error: Failed to apply catalog: Could not retrieve local facts: undefined method `ipv4_loopback?' for "a.b.c.d":String
```

I've created a pull-request chrekh/puppet-hosts/pull/3. Do you think this is a proper fix for these errors?
Otherwise your commit seems to solve compatibility with Ruby 1.8. Thanks for your efforts!

**Comment by chrekh** [comment]
That didn't work.  All my IP:s became loopbacks :)
I changed the tests and added parentheses.  Can you test 76c16da

**Comment by fraenki** [comment]
Sorry for the delay. I've tested https://github.com/chrekh/puppet-hosts/commit/76c16da07f97e487e7a7c678561894a8228595ed and it works perfectly on CentOS 6 and 7. Thanks!

**Comment by chrekh** [comment]
Thanks. I have now merged the branch to master and released a new version to Puppet Forge.
