### ISSUE TITLE
Stack specific aliases for `localhost`

### ISSUE THREAD

**Issue by jcpunk** [chrekh/puppet-hosts#25]
It would be helpful for testing dual stack systems if there was a way to add `localhost4` and `localhost6` (with optional customization) to their relevant entries.

**Comment by chrekh** [comment]
Since entries supplied by class-parameter entries override defaults collected by facts it's possible. Example by hiera:
```yaml
hosts::entries:
  '127.0.0.1':
    - localhost4
  '::1':
    - localhost6
```

**Comment by jcpunk** [comment]
That basically does the trick... alas they are under 'Additional entries' rather than "Loopback", but I can live with that.
