### ISSUE TITLE
Disabling IPv6

### ISSUE THREAD

**Issue by yuri2801** [chrekh/puppet-hosts#8]
Hi chrekh,

We had an issue with your module, that is automatically enabling IPv6 for the link local address, creating connectivity issue on our production environment because it's not IPv6-ready. 

Is it possible to add an parameters to completely disabling the IPv6 if needed? For now, I make a quick and dirty change on our server, and I don't have the time to look for that right now, and not before June. 

greetings,

Yuri

**Comment by chrekh** [comment]
It should be enough for you to set hosts::lo_ipv6: [] either as class param or with hiera.

**Comment by yuri2801** [comment]
I tried that but it wasn't working. It is the "primary address" that is causing the issue, and even by putting both `hosts::lo_ipv6: []` and `hosts::primary_ipv6: []` it was not working. For now I just comment the primary address for IPv6 inside the template becasue I needed a quick fix.

**Comment by chrekh** [comment]
Ok, I'll investigate this

**Comment by yuri2801** [comment]
Thanks a lot

**Comment by chrekh** [comment]
I fail to reproduce.  If I set `hosts::lo_ipv6: []` and `hosts::primary_ipv6: []` all ipv6 adresses gets removed from /etc/hosts.  Are you using hiera? And if so, can you try to debug hiera lookup?

**Comment by garbelini** [comment]
Had the same problem. What worked for me was `primary_ipv6 => ['']` and `lo_ipv6 => ['']`
If set only to `[]` I end up with the ipv6 primary address set.

**Comment by chrekh** [comment]
Thank you for sharing this info. I'm now guessing it has to do with ruby-version that I can't reproduce.
I'll add a boolean parameter to disable ipv6.

**Comment by chrekh** [comment]
I have now released a new version on Puppet Forge with two new boolean parameters, enable_ipv4 and enable_ipv6, both defaults to true.

**Comment by garbelini** [comment]
Thanks for the update!
Tested the new version an and it's much cleaner now!

**Comment by chrekh** [comment]
I think I have found the real bug now.
I have released a new version to Puppet Forge with which it should be possible to use empty lists.
